### ISSUE TITLE
This doesn't work anymore

### ISSUE THREAD

**Issue by xarantolus** [xarantolus/fdroid#3]
It looks like the installation of the F-Droid server doesn't work anymore, thus preventing regeneration of this repo.
Maybe some fork ([search](https://github.com/search?q=xarantolus+-user%3Axarantolus)) has fixed this, not sure.

**Comment by Aeris1One** [comment]
It seems that update.sh uses Windows file format, which doesn't work anymore (but why?) running `dos2unix update.sh` then committing the file seems to solve the issue.

**Comment by xarantolus** [comment]
I think the line endings depend on the platform you clone on (and the `core.autocrlf` git configuration). 
The issue used to be that the installation of the fdroidserver package threw errors, but it looks like it has been fixed.
